=== yumeshio/yumeshio.github.io/json/library.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://yumeshio.com/json/library.schema.json",
	"title": "Library",
	"description": "An entry in the library",
	"type": "object",
	"properties": {
		"title": {
			"type": "string"
		},
		"releaseDate": {
			"type": "string"
		},
		"startDate": {
			"type": "string"
		},
		"purchaseDate": {
			"type": "string"
		},
		"completeDate": {
			"type": "string"
		},
		"status": {
			"type": "string",
			"enum": ["unstarted", "ongoing", "completed", "wishlist"]
		},
		"tags": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"images": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"link": {
			"type": "string"
		}
	}
}

=== yumeshio/yumeshio.github.io/content/library/game/clock-zero.json
{
  "title": "CLOCK ZERO ～終焉の一秒～",
  "releaseDate": "2009-04-24",
  "completeDate": "",
  "images": [
    "https://www.otomate.jp/clock_zero/devote/info/img/jacket.png?cx=0&cy=0&cw=275&ch=530",
    "https://store-jp.nintendo.com/dw/image/v2/BFGJ_PRD/on/demandware.static/-/Sites-all-master-catalog/ja_JP/dwe8ec5970/products/D70010000016154/heroBanner/340cbf1ffeb4deff83493494f3a61e888fef70eb4fdec6b5049ef42a9f6faee9.jpg"
  ],
  "tags": [
    "乙女",
    "",
    "",
    ""
  ],
  "status": "completed",
  "purchaseDate": "2025-04-23"
}
